### ISSUE TITLE
Padrao de codigo

### ISSUE THREAD

**Issue by rlucca** [gabepk/treinamento_aker#3]
Favor verificar no wiki e seguir o padrão de codigo recomendado. É possivel configurar um programa para fazer o padrão de uma maneira muito proxima a da empresa. :)

**Comment by rlucca** [comment]
Alem disso, tem diversos espaço em branco que são desnecessarios no final da linha.

**Comment by gabepk** [comment]
Os espaços em brancos no final das linhas foram removidos. O problema era que eu estava copiando e colando no vim usando Ctrl-Shift-C + Ctrl-Shift-V ao invés de y + p;

**Comment by rlucca** [comment]
hum. OK.
