### ISSUE TITLE
Requisição não esperada, faz o binario morrer

### ISSUE THREAD

**Issue by rlucca** [gabepk/treinamento_aker#5]
O binario esta morrendo por não estar sabendo lidar com alguns tipos de requisições. Uma das requisições usadas nos testes é tentar fazer get em um diretorio e ver como o programa se comporta. O resultado esperado pode ser erro ou um sucesso sem listar nada. Fica a seu criterio.

**Comment by gabepk** [comment]
Ou eu resolvi o problema sem querer, ou eu não consegui reproduzir o erro. Você pode verificar se o erro foi corrigido. Se não foi, pode especificar mais como atingiu o erro, por favor?

Quando eu faço requisição de diretório, por exemplo, eu dou resultado de sucesso e não escrevo nada:

**_Terminal 1 (Mostra que servidor não morre com):_**

**[gabriella@localhost treinamento_aker]$ ./s 8080 ~/Documents/**

/home/gabriella/Documents/server_test/

/home/gabriella/Documents/server_test/cute.jpg



 **_Terminal 2 (Mostra que servidor esta enviando arquivos corretamente):_**

**[gabriella@localhost treinamento_aker]$ wget localhost:8080/server_test/**
--2016-12-09 13:11:35--  http://localhost:8080/server_test/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘index.html.1’

index.html.1              [ <=>                   ]       0  --.-KB/s    in 0s      

2016-12-09 13:11:35 (0.00 B/s) - ‘index.html.1’ saved [0]

**[gabriella@localhost treinamento_aker]$ file index.html**
index.html: empty
**[gabriella@localhost treinamento_aker]$ wget localhost:8080/server_test/cute.jpg**
--2016-12-09 13:12:37--  http://localhost:8080/server_test/cute.jpg
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘cute.jpg’

cute.jpg                  [ <=>                   ] 241.96K  --.-KB/s    in 0.002s  

2016-12-09 13:12:37 (107 MB/s) - ‘cute.jpg’ saved [247771]

**[gabriella@localhost treinamento_aker]$ file cute.jpg** 
cute.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 95", baseline, precision 8, 1440x900, frames 3

**Comment by rlucca** [comment]
Ainda aconteceu o bug, eu estou vendo colhetando mais informações. Mas vamos resolver isso na #4.
